name: Safari Go
favicon: null
layout_spectrum: 0.2468
typography_spectrum: 0.52046
title: 'Youth Workshops & Events'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.5062023871578276
  rhythmicContrast: 0.5
purpose: []
